# SERVER
server:
 port: 5001
 error.whitelabel.enabled: false

spring:
  h2:
    console:
        enabled: true
        path: /h2

multipart:
  enabled: true
  max-file-size: 500Mb
  max-request-size: 500MB

#LOGGING
logging:
  level:
    com.kyushu.autosum: DEBUG

