package com.kyushu.autosum.servicelayer.uploadservices.util;

import com.kyushu.autosum.Application;
import com.kyushu.autosum.servicelayer.util.objecthandler.file.FileHandler;
import org.apache.commons.lang3.RandomStringUtils;
import org.springframework.stereotype.Service;

import java.io.File;

/**
 * Class which offer some useful service for handle file
 * Service : obtain Mime type, convert multipart to file, generate random file name of 4 characters
 *
 * @author ANDRE
 * @date 10/05/16
 */
@Service
public class CreateFileToUpload {

    private static String autoGenerated;

    private static String fileName;

    /**
     * Create the file in the server side
     *
     * @param originalFileName is the name of the file to upload
     * @return the file created
     */
    public static File createFileToUpload(String originalFileName) {

        createFileName(originalFileName);

        File directory = new File(Application.UploadDir.concat("/").concat(autoGenerated));

        directory.mkdirs();

        File file = new File(directory + "/" + fileName);

        file = FileHandler.createNewFile(file);

        return file;
    }


    /**
     * Create the name of the file in server side
     *
     * @param originalFileName is the name of the file to upload
     * @return the name created
     */
    static void createFileName(String originalFileName) {

        // Create the fileName
        generateRandom4Characters();

        fileName = autoGenerated.concat("-").concat(originalFileName);
    }


    /**
     * Generate Filename, random generation of 4 characters (letters and numbers)
     *
     * @return a string of 4 characters
     */
    static void generateRandom4Characters() {

        boolean checkFileExists;

        do {
            // Generate a random string of 4 characters (letters and numbers)
            autoGenerated = RandomStringUtils.random(4, true, true);

            // Check if file exists
            checkFileExists = new File(autoGenerated).exists();

        } while (checkFileExists);

    }

}


